### PR TITLE
Update Hooks up to SDK 33

### PR DESCRIPTION
**Pull request by VD171**

### CODE REVIEW

**Comment by M66B** [comment]
It seems new hook definitions are being added for Android versions before Android 13. This is inevitably going to cause problems for existing users and therefore I can't accept this commit.

Can you please tell me why these new hook definitions are necessary on Android 13 ?

**Comment by VD171** [comment]
All added hooks has same return type and discards parameters/arguments.
So, functionality will not be affected.

Old hooks like "getInstalledPackages(int) and  "getInstalledApplications(int)" were deprecated on API Level 33.
They exist since API Level 1 but probably they will be removed soon.
As we can see here:
https://developer.android.com/reference/android/content/pm/PackageManager

**Comment by VD171** [comment]
I've committed some updates for webview constructors too.

**Comment by VD171** [comment]
Here is the list of existing hooks deprecated on API Level 33:

- public abstract List<ApplicationInfo> getInstalledApplications (int flags)
Added in API level 1
Deprecated in API level 33

- public abstract List<PackageInfo> getInstalledPackages (int flags)
Added in API level 1
Deprecated in API level 33

- public abstract List<PackageInfo> getPackagesHoldingPermissions (String[] permissions, int flags)
Added in API level 18
Deprecated in API level 33

- public abstract List<ResolveInfo> queryIntentActivities (Intent intent, int flags)
Added in API level 1
Deprecated in API level 33

- public abstract List<ResolveInfo> queryIntentActivityOptions (ComponentName caller, Intent[] specifics, Intent intent, int flags)
Added in API level 1
Deprecated in API level 33

- public abstract List<ResolveInfo> queryIntentContentProviders (Intent intent, int flags)
Added in API level 19
Deprecated in API level 33

- public abstract List<ResolveInfo> queryIntentServices (Intent intent, int flags)
Added in API level 1
Deprecated in API level 33

**Comment by M66B** [comment]
I will probably have some time end of this week to look into this more closely.

**Comment by VD171** [comment]
Allright, my dear friend.
Thank you very much for your time and work :-)
Have a nice day !

**Comment by M66B** [comment]
Since I don't want to make changes pre-Android 13, I have only added new hook definitions for minSdk 33.

**Comment by VD171** [comment]
Glad to hear you !
Thank you very much for the best xposed module ever.
Best wishes ❤️

**Pull request closed without merging**
